dim: 2

Lx: [5, 6]
Nx: [10, 10]
rho_0: 10.0
sim_plan: single_sim
sim_type: canonical
output_dir: output
max_iter: 10

components:
  - type: homopolymer
    species: A
    vol_frac: 0.4
    n_segments_per_molecule: 10
  - type: homopolymer
    species: B
    vol_frac: 0.6
    n_segments_per_molecule: 20

outputs:
  grid:
    print_freq: 5
    column_width: 15
    write_header: true
    gnuplot_compatible: true
  lammpstrj:
    print_freq: 5
  summary:
    var_list: ["iter", "u_bond"]
    print_freq: 2
    column_width: 15
    write_header: true
